/**
 * Curated icon vocabulary shared by the website and Sanity Studio.
 * Editors pick from this list (Studio imports it), and `$lib/components/ui/Icon.svelte`
 * maps each name to a tree-shaken Lucide component.
 */
export const ICON_NAMES = [
	'award',
	'badge-check',
	'banknote',
	'bath',
	'bike',
	'blocks',
	'brick-wall',
	'building',
	'building-complex',
	'calculator',
	'calendar-check',
	'car',
	'cctv',
	'clipboard-check',
	'clock',
	'compass',
	'construction',
	'door-open',
	'drafting-compass',
	'droplets',
	'dumbbell',
	'baby',
	'eye',
	'fence',
	'file-check',
	'file-text',
	'flame',
	'gauge',
	'hammer',
	'handshake',
	'hard-hat',
	'heart-handshake',
	'house',
	'key-round',
	'lamp',
	'land-plot',
	'landmark',
	'layers',
	'layout-grid',
	'leaf',
	'lightbulb',
	'map-pin',
	'mountain',
	'paint-roller',
	'pencil-ruler',
	'receipt',
	'recycle',
	'route',
	'ruler',
	'scale',
	'scan-eye',
	'scroll-text',
	'shield-check',
	'shovel',
	'sofa',
	'sparkles',
	'sprout',
	'stamp',
	'store',
	'sun',
	'trees',
	'users',
	'utility-pole',
	'warehouse',
	'waves-ladder',
	'wifi',
	'wind',
	'zap'
] as const;

export type IconName = (typeof ICON_NAMES)[number];
