/**
 * Seed helpers — shared by the demo-mode data layer (SvelteKit) and the
 * Studio seed builder (`studio/seed/build-seed.ts`, run with Node's native
 * TypeScript support). Keep this file free of non-erasable TS syntax.
 */

export type SeedDoc = { _id: string; _type: string; [key: string]: unknown };

/** Placeholder imagery generated by `scripts/generate-demo-images.ts`. */
export const DEMO_IMAGES = {
	hero_tower: { w: 2400, h: 1500, kind: 'tower', tone: 'dusk' },
	og_default: { w: 1200, h: 630, kind: 'tower', tone: 'dusk' },
	tamarind_court: { w: 1600, h: 1100, kind: 'tower', tone: 'day' },
	tamarind_court_dusk: { w: 1600, h: 1100, kind: 'tower', tone: 'dusk' },
	tamarind_site: { w: 1600, h: 1100, kind: 'site', tone: 'day' },
	sage_residences: { w: 1600, h: 1100, kind: 'villa', tone: 'day' },
	sage_villa_dusk: { w: 1600, h: 1100, kind: 'villa', tone: 'dusk' },
	sage_interior: { w: 1600, h: 1100, kind: 'interior', tone: 'day' },
	meridian_works: { w: 1600, h: 1100, kind: 'commercial', tone: 'dusk' },
	meridian_lobby: { w: 1600, h: 1100, kind: 'interior', tone: 'night' },
	palm_grid: { w: 1600, h: 1100, kind: 'plots', tone: 'day' },
	palm_grid_avenue: { w: 1600, h: 1100, kind: 'landscape', tone: 'dawn' },
	terracotta_house: { w: 1600, h: 1100, kind: 'villa', tone: 'night' },
	lakeline: { w: 1600, h: 1100, kind: 'tower', tone: 'dawn' },
	lakeline_pool: { w: 1600, h: 1100, kind: 'amenity', tone: 'day' },
	ivory_row: { w: 1600, h: 1100, kind: 'villa', tone: 'dawn' },
	northfield: { w: 1600, h: 1100, kind: 'plots', tone: 'dusk' },
	interior_living: { w: 1600, h: 1100, kind: 'interior', tone: 'dusk' },
	interior_kitchen: { w: 1600, h: 1100, kind: 'interior', tone: 'dawn' },
	site_structure: { w: 1600, h: 1100, kind: 'site', tone: 'dusk' },
	site_foundation: { w: 1600, h: 1100, kind: 'site', tone: 'dawn' },
	amenity_clubhouse: { w: 1600, h: 1100, kind: 'amenity', tone: 'dusk' },
	landscape_garden: { w: 1600, h: 1100, kind: 'landscape', tone: 'day' },
	office: { w: 1600, h: 1100, kind: 'commercial', tone: 'day' },
	plan_2bhk: { w: 1400, h: 1000, kind: 'plan', tone: 'day' },
	plan_3bhk: { w: 1400, h: 1000, kind: 'plan', tone: 'dawn' },
	plan_villa: { w: 1400, h: 1000, kind: 'plan', tone: 'dusk' },
	plan_plot: { w: 1400, h: 1000, kind: 'plan', tone: 'night' },
	portrait_1: { w: 900, h: 1100, kind: 'portrait', tone: 'day' },
	portrait_2: { w: 900, h: 1100, kind: 'portrait', tone: 'dawn' },
	portrait_3: { w: 900, h: 1100, kind: 'portrait', tone: 'dusk' },
	portrait_4: { w: 900, h: 1100, kind: 'portrait', tone: 'night' },
	portrait_5: { w: 900, h: 1100, kind: 'portrait', tone: 'day' }
} as const;

export type DemoImageName = keyof typeof DEMO_IMAGES;

let keyCounter = 0;
/** Deterministic `_key` generator (stable across runs because module order is stable). */
export function k(): string {
	keyCounter += 1;
	return `k${keyCounter.toString(36).padStart(5, '0')}`;
}

/** Demo image field. Asset refs follow Sanity's `image-<id>-<w>x<h>-<ext>` convention
 *  so width/height can be derived without a network round-trip. */
export function img(name: DemoImageName, alt: string, caption?: string) {
	const d = DEMO_IMAGES[name];
	return {
		_type: 'imageWithAlt',
		alt,
		...(caption ? { caption } : {}),
		asset: { _type: 'reference', _ref: `image-demo${name}-${d.w}x${d.h}-jpg` }
	};
}

/** Demo file field (e.g. a brochure PDF). */
export function file(name: string, title: string) {
	return {
		_type: 'file',
		title,
		asset: { _type: 'reference', _ref: `file-demo${name}-pdf` }
	};
}

export function ref(id: string, withKey = false) {
	return withKey ? { _type: 'reference', _ref: id, _key: k() } : { _type: 'reference', _ref: id };
}

export const refs = (ids: string[]) => ids.map((id) => ref(id, true));

export function slug(current: string) {
	return { _type: 'slug', current };
}

/* ── Portable Text ─────────────────────────────────────────────────────────── */
type Span = { _type: 'span'; _key: string; text: string; marks: string[] };

function spans(text: string): { children: Span[]; markDefs: unknown[] } {
	// Supports **bold** and *italic* inline markers for convenience.
	const children: Span[] = [];
	const re = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
	let last = 0;
	for (const m of text.matchAll(re)) {
		const idx = m.index ?? 0;
		if (idx > last)
			children.push({ _type: 'span', _key: k(), text: text.slice(last, idx), marks: [] });
		const raw = m[0];
		const bold = raw.startsWith('**');
		children.push({
			_type: 'span',
			_key: k(),
			text: raw.slice(bold ? 2 : 1, bold ? -2 : -1),
			marks: [bold ? 'strong' : 'em']
		});
		last = idx + raw.length;
	}
	if (last < text.length)
		children.push({ _type: 'span', _key: k(), text: text.slice(last), marks: [] });
	return { children, markDefs: [] };
}

export function p(text: string) {
	return { _type: 'block', _key: k(), style: 'normal', ...spans(text) };
}
export function h2(text: string) {
	return { _type: 'block', _key: k(), style: 'h2', ...spans(text) };
}
export function h3(text: string) {
	return { _type: 'block', _key: k(), style: 'h3', ...spans(text) };
}
export function quote(text: string) {
	return { _type: 'block', _key: k(), style: 'blockquote', ...spans(text) };
}
export function ul(items: string[]) {
	return items.map((t) => ({
		_type: 'block',
		_key: k(),
		style: 'normal',
		listItem: 'bullet',
		level: 1,
		...spans(t)
	}));
}
export function ol(items: string[]) {
	return items.map((t) => ({
		_type: 'block',
		_key: k(),
		style: 'normal',
		listItem: 'number',
		level: 1,
		...spans(t)
	}));
}
export function callout(tone: 'note' | 'tip' | 'warning', text: string) {
	return { _type: 'callout', _key: k(), tone, text };
}
export function inlineImage(name: DemoImageName, alt: string, caption?: string) {
	return { ...img(name, alt, caption), _key: k() };
}

/** Flatten helper so lists (arrays of blocks) can sit inline in body arrays. */
export function body(...parts: unknown[]) {
	return parts.flat();
}

/* ── Reusable objects ─────────────────────────────────────────────────────── */
export function cta(
	label: string,
	href: string,
	variant: 'primary' | 'secondary' | 'ghost' = 'primary',
	action: 'link' | 'consultation' | 'whatsapp' = 'link'
) {
	return { _type: 'cta', label, href, variant, action };
}

export function stat(value: number, label: string, suffix = '', prefix = '', decimals = 0) {
	return { _type: 'stat', _key: k(), value, label, suffix, prefix, decimals };
}

export function feature(icon: string, title: string, description: string) {
	return { _type: 'feature', _key: k(), icon, title, description };
}

export function seo(title: string, description: string) {
	return { _type: 'seo', title, description };
}
